### PR TITLE
Update omkaragrawal.html

### PR DESCRIPTION
**Pull request by Omkaragrawal**
Task 3 completion

### CODE REVIEW

**Review by amanintech — CHANGES_REQUESTED** [review]
Can you resolve merge conflicts ?

**Comment by Omkaragrawal** [comment]
Sir this was yesterday's PR which wasn't merged and today's PR was, hence this is causing issue. I had asked you on slack, can I do it later, but that very time I made this pr at 4pm yesterday.

**Comment by Omkaragrawal** [comment]
Sir, in today's PR, I moved this file into my folder, so you ca see code there.

**Review by amanintech — APPROVED** [review]

**Review by amanintech — CHANGES_REQUESTED** [review]
Then I guess you should fork back and make the changes and create another PR

**Pull request closed without merging**
